### ISSUE TITLE
Plan November call

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#10]
Wednesday 28 November works for @Gilles86 & @KirstieJane.

- [x] Send out an email to the BIDS mailing list suggesting a few times: 4pm, 5pm, 6pm CET.
    Here's the doodle poll: https://doodle.com/poll/gz787nhx8srv83dg
    Close at end of day on Monday 12 Nov
- [x] Confirm time to BIDS mailing list
- [x] Send invite & zoom link

**Comment by Gilles86** [comment]
My tasks

- [x] Propose text for issue #6 
- [x] Propose text for issue #3 
https://github.com/bids-standard/bep001/tree/suffix_io_sequence_label
- [ ] Collect real data from open data sets (issue #11)

**Comment by KirstieJane** [comment]
Closing! Thank you everyone for coming!
